### ISSUE TITLE
 Starter KEPs to propose

### ISSUE THREAD

**Issue by rikatz** [jayunit100/network-policy-subproject#30]
https://docs.google.com/document/d/1AtWQy2fNa4qXRag9cCp5_HsefD7bxKe3ea2RPn8jnSs/edit#bookmark=id.k7sy1l76o8br

To be discussed in our next meeting

**Comment by jayunit100** [comment]
- port ranges
- remove defaults to the NetworkPolicy API Struct
- namespace by name
- services by name

**Comment by McCodeman** [comment]
@McCodeman to link individual KEP documents

**Comment by rikatz** [comment]
https://docs.google.com/document/d/1_5SpZwvi9KlNMT6psrK1yu4Eo7G2FxyMuHHz-JIHd5Y/edit#

This is the document to be sent to the mailing list and to be presented in sig-network meeting as the 'we want to do this, is everybody ok with that'.

So far during our meeting today we got a +1 of @abhiraut @rikatz @andrewsykim for all the user stories, knowing that each one got their value and different difficulties of implementation

**Comment by jayunit100** [comment]
so, we removed the nodeselector for todays proposal - bc it seems complex and we dont have it worked out entirely yet.

**Comment by rikatz** [comment]
I'm closing this, and will open issues for everyone that will own each of the Keps
