### ISSUE TITLE
Create Port Range Story

### ISSUE THREAD

**Issue by McCodeman** [jayunit100/network-policy-subproject#34]
- Ricardo to own this issue...

**Comment by jayunit100** [comment]
- This will be the first, likely easily digestible attempt at a KEP that we serve as one of many, later composable artifacts that this group will create.

# Technical considerations
- Can we implement this into the network policy operator stuff as a prototypical implementation?
- Named port groups vs port ranges?  
```
I've been thinking about this approach, 
I think it makes more sense in the 'Ports' object, 
where I want to create a PortSet containing ports 80, 443, 8443,
call it HTTPPorts and use this instead of a multiport in a network policy
```
- How many CNIs currently implement this ? (calico, cillim, antrea, openshift-cni, ...)

**Comment by rikatz** [comment]
Will work on this late today.

I would like to review the story and this week (or maximum in the next one, after we review this) create the issue for the kep in the k/enhancements, and the PR for the Kep.

Any thoughts?
