### ISSUE TITLE
Create the issue and Kep for Cluster Scoped Network Policy

### ISSUE THREAD

**Issue by rikatz** [jayunit100/network-policy-subproject#50]
Create the issue and the Kep for Cluster Scoped Network Policy in k/enhancements repo 

@abhiraut it doesn't seem you're member of the project here, but I'm marking you here anyway :D

**Comment by rikatz** [comment]
Issue opened: https://github.com/kubernetes/enhancements/issues/2091

**Comment by abhiraut** [comment]
> Create the issue and the Kep for Cluster Scoped Network Policy in k/enhancements repo
> 
> @abhiraut it doesn't seem you're member of the project here, but I'm marking you here anyway :D

thanks.. @jayunit100 why do you not want me to be a member??? why????

**Comment by rikatz** [comment]
well now @abhiraut is a member, the work is going, and I'm cleaning my issues notifications :P
