### ISSUE TITLE
brainstorming a CRD

### ISSUE THREAD

**Issue by jayunit100** [jayunit100/network-policy-subproject#8]
Mostly thinking out loud, but want to start a thread around a CRD that would be able to generate (i.e. via an operator) v1 downstream networkpolicies.   

Roughly, I think something like this would integrate many of the things people have asked for thus far.

```
NetpolExtended {
    Spec:
        Scope:
            AllNamespaces: true/false
            AllNamespacesRegex: true/false
            IncludedNamespaces: (labels)
            // ^ Pick one
        PortSpec:
            Range: min,max
            []Ports:
            Port
            // ^ Pick one, either a 
        NodeSelectorSpec:
             matchLabels
            // will allow traffic to all nodes in this sector
        ServiceSelectorSpec:
            // will allow traffic to pods in services of this selector
            matchLabels
        NamespacesSelectorSpec:
            // will allow all traffic to all namespaces in this selector
            matchLabels
        K8sDefaultService: true
        KubeDNSService: true
   Status:
        List[Pod,Pod] ConnectedViaNetworkPolicy
        List[Pod,Pod] ConnectedViaClusterlPolicy
}
```

Note i haven't at all thought about cardinality here, no clue wether or not this would work as is .

**Comment by rikatz** [comment]
Here:
```
            AllNamespaces: true/false
            AllNamespacesRegex: true/false
            IncludedNamespaces: (labels)
```

what about having two fields: one with the match behavior (exactly or regex) and the other one with the properly regex and/or the field.

As an example:

```
matchNamespace: regex
namespaceSelector:
  name: "*" # This can be one selector, and here  
```

or 

```
matchNamespace: label
namespaceSelector:
  labels: 
    protected: true
```

**Comment by rikatz** [comment]
I like the idea of using booleans for allowing/denying the access to k8services and k8sdns, just wondering how this turns into a deny rule if you say "no" and someone puts a rule there that allow this. Will the controller remove offending policies?

**Comment by jayunit100** [comment]
deny rules might be another issue we can add in next iteration.  If you dont see any major dysfunction, i think maybe ill commit that file as a v0 of a potential CRD and we can iterate via PR's on the file?

**Comment by rikatz** [comment]
Yeah sure.

I’ve asked about the deny thing mostly because of the boolean k8sapiaccess,
etc. can evolve this in a later PR

Em dom., 23 de ago. de 2020 às 18:44, jay vyas <notifications@github.com>
escreveu:

**Comment by jayunit100** [comment]
:)

**Comment by jayunit100** [comment]
ok, commited to master.  We can keep this issue open until we feel like were close to an implementation that might cover a good 75% of the cases were interested in

**Comment by jayunit100** [comment]
now that we have this in master and Matts repo mattfenwick/kube-prototypes is up (https://github.com/mattfenwick/kube-prototypes/tree/master/pkg/netpol/crd) we can follow on in PRs
